language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

php:
  - 7.1
  - 7
  - 5.6
  - nightly
  - hhvm

before_install:
  - composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN

install:
  - composer update --no-interaction --prefer-stable --prefer-dist --no-suggest --no-scripts --no-plugins $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit --verbose --coverage-clover=build/logs/clover.xml
  - ./vendor/bin/behat --format=progress --strict

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
